### ISSUE TITLE
Custom renderer for each database record is needed

### ISSUE THREAD

**Issue by chfw** [pyexcel-webwares/django-excel#24]
custom renderer could allow developer to customize their data before it is given into the response. hence, it would help a few developer issues such as: #19 #22 .

**Comment by sailf** [comment]
@chfw  求中文文档·

**Comment by chfw** [comment]
中文文档要从常计议了。英文文档现在还不够全。等pyexcel v0.6.0之后，考虑中文文档。

**Comment by orochiisfun** [comment]
@chfw ，请问下，save_book_to_database这个从excel保存到数据库，对重复数据怎么处理，直接报错么？有创建或更新功能么，像creat_or_update.还有这个文档有中文么？如果没有，我想找时间翻译下，只是为了学习，如果能出力当然最好。期望回复，谢谢！

**Comment by chfw** [comment]
终于要实现诺言了，请关注 http://django.pyexcel.org/zh/latest/
