### ISSUE TITLE
Broken Link to "TOC"

### ISSUE THREAD

**Issue by guettli** [pyexcel-webwares/django-excel#43]
If I click on "table of content" on this page:
   http://django-excel.readthedocs.io/en/latest/#

I get: 404 file not found:

http://django-excel.readthedocs.io/en/latest/contents.html

**Comment by chfw** [comment]
yep, I see. I will disable the link for now. The documentation has always been a single page documentation. 

But soon, I will expand it into two pages. The extra page will explain the new features brought by pyexcel version 0.6.0: data visualisation.
