### ISSUE TITLE
The exported field has choices

### ISSUE THREAD

**Issue by glinxx** [pyexcel-webwares/django-excel#45]
There is a choices in the exported field. How do you display the corresponding value?

`class Introduction(models.Model):
    INTRODUCTIO_STATUS_CHOICES = ( (0,'未确认'),(1,'已确认'),)
    status = models.IntegerField(u"状态",choices = CARD_STATUS_CHOICES,default=1)
    (...)

column_names = ['org__shop', 'staff_name', 'staff_mobile', 'invitation_name', 'invitation_mobile', 'sale_contract', 'car_model', 'bonus', 'remark', 'invitation_time', 'introductio_status', 'editor__truename', 'edit_time']
`

**Comment by chfw** [comment]
please pass on an extra parameter `row_renderer=your_custom_renderer` to the signature functions of django-excel:

```
def your_custom_renderer(row):
     row[10]= CARD_STATUS_CHOICES[row[10]] # 11th place is introduction_status
     return row
```
