### ISSUE TITLE
export xls file type error

### ISSUE THREAD

**Issue by nloneday** [pyexcel-webwares/django-excel#47]
- xls
`make_response(sheet, "xls", file_name=filename)`
`OSError: No content, file name. Nothing is given`

- xlsx
`make_response(sheet, "xlsx", file_name=filename)`
`Success`

**Comment by chfw** [comment]
please show me your package list. you can get it using `pip freeze` from your current python env.

**Comment by fergbrain** [comment]
I have the same issue, but also doesn't work for xlsx either. Here's the output from pip freeze:
```
Babel==2.6.0
beautifulsoup4==4.6.3
Django==2.1.1
django-bootstrap-themes==3.3.6
django-bootstrap3==11.0.0
django-bootstrap4==0.0.7
django-crispy-forms==1.7.2
django-excel==0.0.10
-e git://github.com/AndrewIngram/django-extra-views.git@aa58167af84d89feea286f9567a72cc5941360e4#egg=django_extra_views
django-localflavor==2.1
django-phonenumber-field==2.0.1
GDAL==2.3.1
lml==0.0.4
nose==1.3.7
numpy==1.15.1
phonenumbers==8.9.14
pyexcel==0.5.9.1
pyexcel-io==0.5.9.1
pyexcel-webio==0.1.4
pytz==2018.5
six==1.11.0
texttable==1.4.0
```

**Comment by chfw** [comment]
Contrary to battery included idea, pyexcel is pick-your-own-cherry. So please install pyexcel-xlsx.

**Comment by fergbrain** [comment]
Well, I feel like an idiot now. Thanks :)

I also had to install `XlsxWriter`

**Comment by chfw** [comment]
Then it is pyexcel-xlsxw
