### ISSUE TITLE
Create a file in memory (not an uploaded file) and save to FileField default_storage

### ISSUE THREAD

**Issue by coler-j** [pyexcel-webwares/django-excel#50]
If I was to create a file-like csv object in memory like so:

    output_stream = io.StringIO()
    sheet = pyexcel.get_sheet(records=data)
    sheet.save_to_memory(file_type='csv', stream=output_stream)

What can I do to save the file like object in `output_stream` to a file on my default_storage backend with Django?

    class Example(models.Model):
        model_file = models.FileField(upload_to='', max_length=255, blank=True, null=True)

I've tried something like: 

    self.model_file.save(filename, ContentFile(output_stream.read()))

But I get the following error:
"TypeError: ('`data` must be bytes, received', <class 'str'>)"

**Comment by chfw** [comment]
csv stream are of string type. what if you do:

`self.model_file.save(filename, ContentFile(output_stream.read().encode()))`

have you considered: `sheet.save_as("your_filename.your_file_type")`
