### ISSUE TITLE
on tutorial, compiling test should install django 1.11 not 2

### ISSUE THREAD

**Issue by elfelround** [pyexcel-webwares/django-excel#51]
the tutorial on the site
http://django-excel.readthedocs.io/en/latest/

compiles django 2

its stated that only up to 1.11 works so a step that changes requirements.txt to django==1.11.9 should be added

**Comment by chfw** [comment]
yeah..but I think it is time for me to getting the tutorial working under django 2.0.

someone has told that the middleware itself works well with django 2.0. but my tests is not compatible with django 2.0 so I have no proof.
