### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by riyenas0925** [pyexcel-webwares/django-excel#52]
Hello First of all, I am gratefully using djang-excel, I can not speak English well.

First, can I store only certain columns in the database?

In the code below, I want to store only the test2 column in the database.

```
<Current code>
<views>

request.FILES['file'].save_book_to_database(
				models=[UserSub],
				initializers=[None],
				mapdicts=[{'test1': 'number', 'test2': 'subject'}],
				keyword=[0]
			)

<models>
class UserSub(models.Model):
    number=models.CharField(max_length=10)
    subject=models.CharField(max_length=15)

    def __str__(self):
        return self.subject
```

**Comment by chfw** [comment]
surely, you can as long as your db model won't have: `not null` and you do not omit `primary key` if it is not auto-generated.

**Comment by riyenas0925** [comment]
First of all, thank you for your reply.

Current excel file contents are as follows:
![kakaotalk_20181213_075818492](https://user-images.githubusercontent.com/32615702/49904309-19c5f080-fead-11e8-82f7-708b7671b281.png)

Do I have to save and use all test1,test2,test3 of Excel to use the above test2 data?
Is there any way to store only test2 in the database?

**Comment by chfw** [comment]
alright, then you will have to use `request.FILES['file'].get_sheet()` first, then filter out the unwanted data before saving, here are the tutorial for pyexcel, which is the core library for opening the excel sheets: https://pyexcel.readthedocs.io/en/latest

**Comment by riyenas0925** [comment]
Thanks!

**Comment by riyenas0925** [comment]
Thanks for your help.

The current model is set to Sheet1, and the Excel sheet name is set to Sheet1.

However, if the name of the Excel sheet is sheet1, it works, but if it contains uppercase letters like Sheet1, an error occurs.

![image](https://user-images.githubusercontent.com/32615702/49915866-42fd7580-fedb-11e8-87c6-c460a84828af.png)

How do I read an Excel file named Sheet1?
