### ISSUE TITLE
How dow I format individual fields from a queryset in a make_response_from_querysets

### ISSUE THREAD

**Issue by VidJa** [pyexcel-webwares/django-excel#54]
I'm exporting a queryset including datetime fields. they are displayed as 2019-02-07T12:22:44.938770+00:00 in my exported sheet

How would I format these dates? Should I go via an array?

**Comment by chfw** [comment]
when you will need custom formatting, you will need to use [get_sheet](http://django.pyexcel.org/en/latest/#django_excel.ExcelMixin.get_sheet) and do the formatting before you do the export.

here is the more information on the [get_sheet](http://docs.pyexcel.org/en/v0.6.0/generated/pyexcel.get_sheet.html#pyexcel.get_sheet) and when you are done with the formatting, you can use [make_response](http://django.pyexcel.org/en/latest/#django_excel.make_response)
