### ISSUE TITLE
How do I ignore a row or column when import data use save_to_database?

### ISSUE THREAD

**Issue by zxh326** [pyexcel-webwares/django-excel#55]

**Comment by chfw** [comment]
sorry for the late response, please read the function spec [here](http://docs.pyexcel.org/en/v0.5.3/generated/pyexcel.isave_as.html#pyexcel.isave_as). you can find start_row, row_limit and start_column, column_limit helpful.

And if they are not, you can consider [get_sheet](http://django.pyexcel.org/en/latest/#django_excel.ExcelMixin.get_sheet), do data manipulation first, then save to excel file.

**Comment by zxh326** [comment]
thx, I found `skip_row_func` and `skip_column_func` helpful for me
