### ISSUE TITLE
Incorrect message on file not found

### ISSUE THREAD

**Issue by bdb112** [pyexcel-webwares/django-excel#56]
see next comment

**Comment by bdb112** [comment]
If a non-existent file is opened e..g
pyexcel_ods.read_data('/tmp/odf/test.os') # deliberate typo in name, works if no type
The error message is:
NoSupportingPluginFound: No suitable library found for os

My simple fix is, just before

reader = READERS.get_a_plugin(file_type, library)
in /pyexcel_io/io.py, insert

    import os  # should be in header
    if not os.path.exists(file_name):
        raise IOError(file_name + ' not found')

I have only tested this with ods (spreadsheet) files.

**Comment by chfw** [comment]
You are right. Should have tested the file existence first.
