### ISSUE TITLE
build failed with django 3.1.1

### ISSUE THREAD

**Issue by chfw** [pyexcel-webwares/django-excel#63]
https://travis-ci.org/github/pyexcel-webwares/django-excel/jobs/730670059

**Comment by minhlongdo** [comment]
@chfw is it ok for me to pick this one up?

**Comment by chfw** [comment]
Yep, Please go ahead.

**Comment by minhlongdo** [comment]
@chfw it seems to a pre-Django 1.10 backward compatibility issue.
I think `django-excel` should still support Django apps that are using the pre-Django 1.10 middleware and later remove this if-statement when it has been decided that `django-excel` does not support pre-Django 1.10 versions anymore.
Therefore, I am suggesting like this in the `settings.py` file to fix this issue, what do you think?
```
import django

COMMON_MIDDLEWARE = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
)

if django.VERSION[0] >= 1:
    MIDDLEWARE = (
        *COMMON_MIDDLEWARE,
        'django.middleware.security.SecurityMiddleware'
    )

else:
    MIDDLEWARE_CLASSES = COMMON_MIDDLEWARE
```

**Comment by chfw** [comment]
Looks good. One question: why is COMMON_MIDDLEWARE assigned back to MIDDLEWARE?

**Comment by chfw** [comment]
You can fort the repo and add django 3.1.1 back with your modifications, 

https://github.com/pyexcel-webwares/django-excel/commit/c56124f46968872187f514d3842c80d7e488e4a1

the CI test shall start.

**Comment by minhlongdo** [comment]
> Looks good. One question: why is COMMON_MIDDLEWARE assigned back to MIDDLEWARE?

My understanding is that `MIDDLEWARE` is supposed to replace the old `MIDDLWARE_CLASSES`.
The only difference between `MIDDLEWARE` and `MIDDLEWARE_CLASSES` is that by default `MIDDLEWARE` has `django.middleware.security.SecurityMiddleware` and what was previously defined in the old `MIDDLEWARE_CLASSES` (defined in `COMMON_MIDDLEWARE`). To avoid code repetition, I have used `COMMON_MIDDLEWARE` to put all common middlewares together.

**Comment by chfw** [comment]
I see. `COMMON_MIDDLEWARE` was not a magic variable for django 3.x

**Comment by chfw** [comment]
@minhlongdo ,thanks for your help! Appreciated.
