### ISSUE TITLE
jump column

### ISSUE THREAD

**Issue by bengoshii** [pyexcel-webwares/django-excel#65]
Hi:
I want to import an excel-file; this file is standardized. I have some columns in the excel-file which I have not in my model (and I do not need). I could edit the excel-file for every import but I would prefere to "skip" some columns. I tried to write a mapdicts=[['foo', '', 'bar']] for skip the column between A and C. Is there a way?
Thanks,
bengoshi

**Comment by chfw** [comment]
There must be a way. Let me have a look.

**Comment by chfw** [comment]
Please upgrade to pyexcel-io 0.6.4.

and follow the example here:

https://github.com/pyexcel-webwares/django-excel/blob/master/polls/views.py#L245

**Comment by chfw** [comment]
the tutorial has covered it too: http://django.pyexcel.org/en/latest/#handle-data-import
