### ISSUE TITLE
start test got wrong

### ISSUE THREAD

**Issue by jackuboot** [pyexcel-webwares/django-excel#67]
atfter clone the project
then init the migarations
finally....to run the temple test, got the wrong ：

pyexcel.exceptions.FileTypeNotSupported: File type 'handsontable.html' is not supported for write.

**Comment by chfw** [comment]
please do this:

`pip install -r tests/requirements.txt`

**Comment by jackuboot** [comment]
> please do this:
> 
> `pip install -r tests/requirements.txt`

thats great, thanks!!
