### ISSUE TITLE
Can't get XLSX support working

### ISSUE THREAD

**Issue by KnowYourselves** [pyexcel-webwares/django-excel#68]
Hello!

Since XLRD dropped XLSX support I've been unable to get support for this type of file working.

I have the following form:

```python
class UploadFileForm(forms.Form):
    """
    Form to upload bank movements csv/xls/xlsx file
    """

    file = forms.FileField(
        validators=[FileExtensionValidator(['xls', 'xlsx', 'csv'])],
    )
```

I also have a form view that gives the error `XLRD Error: Excel xlsx file; not supported` when the following code is run in the `form_valid` function:

```python
movements_data = form.cleaned_data['file'].get_array()
```

I've tried a variety of things so it doesn't use XLRD but nothing seems to work. I followed the documentation and installed `pyexcel-xls` and `pyexcel-xlsx`. I also tried importing `pyexcel.ext.xlsx` both on the view and the form file to no avail.

Any surefire way to get XLSX support working again?

Thanks!

EDIT: I have found that the `library` kwarg lets me bypass XLRD and use `pyexcel-xlsx` directly, but wouldn't this break support for csv, xls, and others?

**Comment by chfw** [comment]
please install latest pyexcel-xls, which has pinned on older version of xlrd.

**Comment by chfw** [comment]
> EDIT: I have found that the library kwarg lets me bypass XLRD and use pyexcel-xlsx directly, but wouldn't this break support for csv, xls, and others?

with 'library' parameter, it assumes that you explicitly know the file type so you can choose the pyexcel plugin. but I hope you will not force pyexcel-xlsx to read a csv file :)

**Comment by chfw** [comment]
https://github.com/pyexcel/pyexcel-xls/pull/41

**Comment by KnowYourselves** [comment]
Thx! I did install it, but it didn't work. In the end, I deleted all the packages, cleaned the cache, installed them again, and now it's working like a charm. Thx for the response!
